---
sidebar: sidebar 
permalink: get-started/install_acc.html 
keywords: astra installation, install astra control center, how to install astra control, deploy, download from netapp support 
summary: 若要在解決某些環境先決條件之後安裝Astra Control Center、您必須下載套裝軟組、並依照所述步驟安裝。 
---
= 使用標準程序安裝Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


若要安裝 Astra Control Center，請從 NetApp 支援網站下載安裝套件，然後執行下列步驟，在您的環境中安裝 Astra Control Center Operator 和 Astra Control Center。您可以使用此程序、在連線網際網路或無線環境中安裝Astra Control Center。

對於Red Hat OpenShift環境、您可以使用 link:../get-started/acc_operatorhub_install.html["替代程序"] 使用OpenShift作業系統集線器安裝Astra Control Center。

.您需要的產品
* link:requirements.html["開始安裝之前、請先準備好環境以進行Astra Control Center部署"]。
* 如果您已設定或想要在環境中設定Pod安全性原則、請熟悉Pod安全性原則、以及這些原則如何影響Astra Control Center安裝。請參閱 link:understand-psp-restrictions.html["瞭解Pod安全性原則限制"]。
* 確保所有叢集操作員都處於健全狀態且可用。
+
[source, sh]
----
kubectl get clusteroperators
----
* 確保所有API服務均處於健全狀態且可供使用：
+
[source, sh]
----
kubectl get apiservices
----
* 確保您打算使用的Astra FQDN可路由傳送至此叢集。這表示您在內部DNS伺服器中有DNS項目、或是使用已註冊的核心URL路由。
* 如果叢集中已存在認證管理程式、您需要執行某些作業 link:../get-started/cert-manager-prereqs.html["必要步驟"] 因此Astra Control Center不會安裝自己的認證管理程式。


.關於這項工作
Astra Control Center安裝程序會執行下列作業：

* 將Astra元件安裝至 `netapp-acc` （或自訂命名）命名空間。
* 建立預設帳戶。
* 建立預設的管理使用者電子郵件地址和預設的一次性密碼。此使用者在系統中被指派第一次登入UI所需的擁有者角色。
* 協助您判斷所有Astra Control Center Pod都在執行中。
* 安裝Astra UI。



IMPORTANT: （僅適用於Astra Data Store Early Access Program（EAP）版本）如果您打算使用Astra Control Center管理Astra Data Store並啟用VMware工作流程、請僅在上部署Astra Control Center `pcloud` 命名空間而非 `netapp-acc` 命名空間或自訂命名空間、請參閱本程序步驟。


IMPORTANT: 請勿在整個安裝程序期間執行下列命令、以免刪除所有Astra Control Center Pod： `kubectl delete -f astra_control_center_operator_deploy.yaml`


NOTE: 如果您使用的是Red Hat的Podman而非Docker Engine、則可以使用Podman命令來取代Docker命令。

.步驟
若要安裝Astra Control Center、請執行下列步驟：

* <<下載並解壓縮Astra Control Center套裝組合>>
* <<安裝NetApp Astra kubecl外掛程式>>
* <<將映像新增至本機登錄>>
* <<設定具有驗證需求之登錄的命名空間和機密>>
* <<安裝Astra Control Center操作員>>
* <<設定Astra控制中心>>
* <<完整的Astra控制中心和操作員安裝>>
* <<驗證系統狀態>>
* <<設定入口以進行負載平衡>>
* <<登入Astra Control Center UI>>




== 下載並解壓縮Astra Control Center套裝組合

. 下載Astra Control Center套裝組合 (`astra-control-center-[version].tar.gz`）從 https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["NetApp 支援網站"^]。
. 從下載Astra Control Center認證與金鑰的壓縮檔 https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["NetApp 支援網站"^]。
. （可選）使用以下命令驗證套件的簽名：
+
[source, sh]
----
openssl dgst -sha256 -verify AstraControlCenter-public.pub -signature astra-control-center-[version].tar.gz.sig astra-control-center-[version].tar.gz
----
. 擷取影像：
+
[source, sh]
----
tar -vxzf astra-control-center-[version].tar.gz
----




== 安裝NetApp Astra kubecl外掛程式

NetApp Astra `kubectl` 命令列外掛程式可在執行與部署及升級Astra Control Center相關的一般工作時節省時間。

.您需要的產品
NetApp為不同的CPU架構和作業系統提供外掛程式的二進位檔。執行此工作之前、您必須先瞭解您的CPU和作業系統。在Linux和Mac作業系統上、您可以使用 `uname -a` 命令來收集此資訊。

.步驟
. 列出可用的NetApp Astra `kubectl` 外掛程式二進位檔、並記下作業系統和CPU架構所需的檔案名稱：
+
[source, sh]
----
ls kubectl-astra/
----
. 將檔案複製到與標準相同的位置 `kubectl` 公用程式：在此範例中 `kubectl` 公用程式位於 `/usr/local/bin` 目錄。更換 `<binary-name>` 使用您需要的檔案名稱：
+
[source, sh]
----
cp kubectl-astra/<binary-name> /usr/local/bin/kubectl-astra
----




== 將映像新增至本機登錄

. 為您的Container引擎完成適當的步驟順序：


[role="tabbed-block"]
====
.Docker
--
. 變更至Astra目錄：
+
[source, sh]
----
cd acc
----
. [Subforte_image_local_register_push]將Astra Control Center映像目錄中的套件映像推送到本機登錄。執行命令之前、請先進行下列替代：
+
** 以Astra Control套件檔案名稱取代bunder_file（例如、 `acc.manifest.yaml`）。
** 將my_registry取代為Docker儲存庫的URL。
** 以使用者名稱取代my_register_user。
** 以登錄的授權權杖取代my_register_token。
+
[source, sh]
----
kubectl astra packages push-images -m BUNDLE_FILE -r MY_REGISTRY -u MY_REGISTRY_USER -p MY_REGISTRY_TOKEN
----




--
.Podman
--
. 登入您的登錄：
+
[source, sh]
----
podman login [your_registry_path]
----
. 執行下列指令碼、依照註解中的說明進行<your _inforation>替換：
+
[source, sh]
----
# You need to be at the root of the tarball.
# You should see these files to confirm correct location:
#   acc.manifest.yaml
#   acc/

# Replace <YOUR_REGISTRY> with your own registry (e.g registry.customer.com or registry.customer.com/testing, etc..)
export REGISTRY=<YOUR_REGISTRY>
export PACKAGENAME=acc
export PACKAGEVERSION=22.08.1-26
export DIRECTORYNAME=acc
for astraImageFile in $(ls ${DIRECTORYNAME}/images/*.tar) ; do
  # Load to local cache
  astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image(s): //')

  # Remove path and keep imageName.
  astraImageNoPath=$(echo ${astraImage} | sed 's:.*/::')

  # Tag with local image repo.
  podman tag ${astraImage} ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}

  # Push to the local repo.
  podman push ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
done
----


--
====


== 設定具有驗證需求之登錄的命名空間和機密

. 匯出Astra Control Center主機叢集的KUBECCONFIG：
+
[source, sh]
----
export KUBECONFIG=[file path]
----
. 如果您使用需要驗證的登錄、則需要執行下列動作：
+
.. 建立 `netapp-acc-operator` 命名空間：
+
[source, sh]
----
kubectl create ns netapp-acc-operator
----
+
回應：

+
[listing]
----
namespace/netapp-acc-operator created
----
.. 為建立秘密 `netapp-acc-operator` 命名空間。新增Docker資訊並執行下列命令：
+

NOTE: 預留位置 `your_registry_path` 應與您先前上傳的影像位置相符（例如、 `[Registry_URL]/netapp/astra/astracc/22.08.1-26`）。

+
[source, sh]
----
kubectl create secret docker-registry astra-registry-cred -n netapp-acc-operator --docker-server=[your_registry_path] --docker-username=[username] --docker-password=[token]
----
+
回應範例：

+
[listing]
----
secret/astra-registry-cred created
----
+

NOTE: 如果您在產生機密之後刪除命名空間、則需要在重新建立命名空間之後重新產生命名空間的機密。

.. 建立 `netapp-acc` （或自訂命名）命名空間。
+
[source, sh]
----
kubectl create ns [netapp-acc or custom namespace]
----
+
回應範例：

+
[listing]
----
namespace/netapp-acc created
----
.. 為建立秘密 `netapp-acc` （或自訂命名）命名空間。新增Docker資訊並執行下列命令：
+
[source, sh]
----
kubectl create secret docker-registry astra-registry-cred -n [netapp-acc or custom namespace] --docker-server=[your_registry_path] --docker-username=[username] --docker-password=[token]
----
+
回應

+
[listing]
----
secret/astra-registry-cred created
----
.. [Substete_kubeconfig _secret ]（選用）如果您希望叢集在安裝後由Astra Control Center自動管理、請確定您在Astra Control Center命名空間中提供了要使用此命令部署的kubeconfig作為機密：
+
[source, sh]
----
kubectl create secret generic [acc-kubeconfig-cred or custom secret name] --from-file=<path-to-your-kubeconfig> -n [netapp-acc or custom namespace]
----






== 安裝Astra Control Center操作員

. 變更目錄：
+
[source, sh]
----
cd manifests
----
. 編輯Astra Control Center營運者部署Yaml (`astra_control_center_operator_deploy.yaml`）以參考您的本機登錄和機密。
+
[source, sh]
----
vim astra_control_center_operator_deploy.yaml
----
+

NOTE: 附註的Y反 洗錢範例遵循下列步驟。

+
.. 如果您使用需要驗證的登錄、請取代的預設行 `imagePullSecrets: []` 提供下列功能：
+
[source, sh]
----
imagePullSecrets:
- name: <astra-registry-cred>
----
.. 變更 `[your_registry_path]` 適用於 `kube-rbac-proxy` 映像到您在中推入映像的登錄路徑 <<substep_image_local_registry_push,上一步>>。
.. 變更 `[your_registry_path]` 適用於 `acc-operator-controller-manager` 映像到您在中推入映像的登錄路徑 <<substep_image_local_registry_push,上一步>>。
.. （若為使用Astra Data Store預覽的安裝）請參閱此已知問題 https://docs.netapp.com/us-en/astra-data-store-2112/release-notes/known-issues.html#mongodb-deployment-with-default-liveness-probe-value-fails-with-pods-in-crash-loop["儲存類別資源配置工具、以及您需要對Y反 洗錢進行的其他變更"^]。
+
[listing, subs="+quotes"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        *image: [your_registry_path]/kube-rbac-proxy:v4.8.0*
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        *image: [your_registry_path]/acc-operator:[version x.y.z]*
        imagePullPolicy: IfNotPresent
      *imagePullSecrets: []*
----


. 安裝Astra Control Center操作員：
+
[source, sh]
----
kubectl apply -f astra_control_center_operator_deploy.yaml
----
+
回應範例：

+
[listing]
----
namespace/netapp-acc-operator created
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io created
role.rbac.authorization.k8s.io/acc-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role created
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role created
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding created
configmap/acc-operator-manager-config created
service/acc-operator-controller-manager-metrics-service created
deployment.apps/acc-operator-controller-manager created
----
. 確認Pod正在執行：
+
[source, sh]
----
kubectl get pods -n netapp-acc-operator
----




== 設定Astra控制中心

. 編輯Astra Control Center自訂資源（CR）檔案 (`astra_control_center_min.yaml`）進行帳戶、AutoSupport 功能、登錄及其他必要的設定：
+

NOTE: `astra_control_center_min.yaml` 為預設的CR、適用於大多數安裝。請熟悉所有資訊 link:../get-started/acc_cluster_cr_options.html["CR選項及其潛在價值"] 確保您的環境正確部署Astra Control Center。如果您的環境需要額外的自訂功能、您可以使用 `astra_control_center.yaml` 作為替代的CR.

+
[source, sh]
----
vim astra_control_center_min.yaml
----
+

IMPORTANT: 如果您使用的登錄不需要授權、則必須刪除  `secret` 行內 `imageRegistry` 否則安裝將會失敗。

+
.. 變更 `[your_registry_path]` 移至您在上一個步驟中推送映像的登錄路徑。
.. 變更 `accountName` 字串至您要與帳戶建立關聯的名稱。
.. 變更 `astraAddress` 字串至您要在瀏覽器中用來存取Astra的FQDN。請勿使用 `http://` 或 `https://` 地址中。複製此FQDN以供在中使用 <<登入Astra Control Center UI,後續步驟>>。
.. 變更 `email` 字串至預設的初始系統管理員位址。複製此電子郵件地址以供在中使用 <<登入Astra Control Center UI,後續步驟>>。
.. 變更 `enrolled` for解決方案AutoSupport `false` 適用於沒有網際網路連線或無法保留的網站 `true` 適用於連線站台。
.. 如果您使用外部cert管理程式、請將下列行新增至 `spec`：
+
[source, sh]
----
spec:
  crds:
    externalCertManager: true
----
.. （選用）新增名字 `firstName` 和姓氏 `lastName` 與帳戶相關聯的使用者。您可以在UI中立即或稍後執行此步驟。
.. （選用）變更 `storageClass` 如果您的安裝需要、請將其值加到另一個Trident storageClass資源。
.. （選用）如果您希望叢集在安裝後由Astra Control Center自動管理、而且您已經擁有 <<substep_kubeconfig_secret,已建立包含此叢集之Kbeconfig的秘密>>下、將新欄位新增至名為的Yaml檔案、以提供機密名稱 `astraKubeConfigSecret: "acc-kubeconfig-cred or custom secret name"`
.. 請完成下列其中一個步驟：
+
*** *其他入侵控制器（擷取類型：一般）*：這是Astra控制中心的預設動作。部署Astra Control Center之後、您需要設定入口控制器、以URL顯示Astra Control Center。
+
預設的Astra Control Center安裝會設定其閘道 (`service/traefik`）的類型 `ClusterIP`。此預設安裝需要您額外設定Kubernetes IngresController / Ingress、才能將流量路由傳送至該控制器。如果您想要使用入口、請參閱 link:../get-started/install_acc.html#set-up-ingress-for-load-balancing["設定入口以進行負載平衡"]。

*** *服務負載平衡器（擷取類型：AccTraefik）*：如果您不想安裝IngressController或建立Ingress資源、請設定 `ingressType` 至 `AccTraefik`。
+
這會部署Astra控制中心 `traefik` 作為Kubernetes負載平衡器類型服務的閘道。

+
Astra Control Center使用「負載平衡器」類型的服務 (`svc/traefik` （在Astra Control Center命名空間中）、並要求指派可存取的外部IP位址。如果您的環境允許負載平衡器、但您尚未設定負載平衡器、則可以使用MetalLB或其他外部服務負載平衡器、將外部IP位址指派給服務。在內部DNS伺服器組態中、您應該將Astra Control Center所選的DNS名稱指向負載平衡的IP位址。

+

NOTE: 如需有關「負載平衡器」和入口服務類型的詳細資訊、請參閱 link:../get-started/requirements.html["需求"]。





+
[listing, subs="+quotes"]
----
apiVersion: astra.netapp.io/v1
kind: AstraControlCenter
metadata:
  name: astra
spec:
  *accountName: "Example"*
  astraVersion: "ASTRA_VERSION"
  *astraAddress: "astra.example.com"*
  *astraKubeConfigSecret: "acc-kubeconfig-cred or custom secret name"*
  *ingressType: "Generic"*
  autoSupport:
    *enrolled: true*
  *email: "[admin@example.com]"*
  *firstName: "SRE"*
  *lastName: "Admin"*
  imageRegistry:
    *name: "[your_registry_path]"*
    *secret: "astra-registry-cred"*
  *storageClass: "ontap-gold"*
----




== 完整的Astra控制中心和操作員安裝

. 如果您尚未在上一步中執行此動作、請建立 `netapp-acc` （或自訂）命名空間：
+
[source, sh]
----
kubectl create ns [netapp-acc or custom namespace]
----
+
回應範例：

+
[listing]
----
namespace/netapp-acc created
----
. 在中安裝Astra Control Center `netapp-acc` （或自訂）命名空間：
+
[source, sh]
----
kubectl apply -f astra_control_center_min.yaml -n [netapp-acc or custom namespace]
----
+
回應範例：

+
[listing]
----
astracontrolcenter.astra.netapp.io/astra created
----




== 驗證系統狀態


NOTE: 如果您偏好使用OpenShift、您可以使用相似的相關命令來進行驗證步驟。

. 驗證是否已成功安裝所有系統元件。
+
[source, sh]
----
kubectl get pods -n [netapp-acc or custom namespace]
----
+
每個Pod的狀態應為 `Running`。部署系統Pod可能需要幾分鐘的時間。

+
.回應範例
[%collapsible]
====
[listing, subs="+quotes"]
----
NAME                                     READY  STATUS   RESTARTS AGE
acc-helm-repo-6b44d68d94-d8m55           1/1    Running  0        13m
activity-78f99ddf8-hltct                 1/1    Running  0        10m
api-token-authentication-457nl           1/1    Running  0        9m28s
api-token-authentication-dgwsz           1/1    Running  0        9m28s
api-token-authentication-hmqqc           1/1    Running  0        9m28s
asup-75fd554dc6-m6qzh                    1/1    Running  0        9m38s
authentication-6779b4c85d-92gds          1/1    Running  0        8m11s
bucketservice-7cc767f8f8-lqwr8           1/1    Running  0        9m31s
certificates-549fd5d6cb-5kmd6            1/1    Running  0        9m56s
certificates-549fd5d6cb-bkjh9            1/1    Running  0        9m56s
cloud-extension-7bcb7948b-hn8h2          1/1    Running  0        10m
cloud-insights-service-56ccf86647-fgg69  1/1    Running  0        9m46s
composite-compute-677685b9bb-7vgsf       1/1    Running  0        10m
composite-volume-657d6c5585-dnq79        1/1    Running  0        9m49s
credentials-755fd867c8-vrlmt             1/1    Running  0        11m
entitlement-86495cdf5b-nwhh2             1/1    Running  2        10m
features-5684fb8b56-8d6s8                1/1    Running  0        10m
fluent-bit-ds-rhx7v                      1/1    Running  0        7m48s
fluent-bit-ds-rjms4                      1/1    Running  0        7m48s
fluent-bit-ds-zf5ph                      1/1    Running  0        7m48s
graphql-server-66d895f544-w6hjd          1/1    Running  0        3m29s
identity-744df448d5-rlcmm                1/1    Running  0        10m
influxdb2-0                              1/1    Running  0        13m
keycloak-operator-75c965cc54-z7csw       1/1    Running  0        8m16s
krakend-798d6df96f-9z2sk                 1/1    Running  0        3m26s
license-5fb7d75765-f8mjg                 1/1    Running  0        9m50s
login-ui-7d5b7df85d-l2s7s                1/1    Running  0        3m20s
loki-0                                   1/1    Running  0        13m
metrics-facade-599b9d7fcc-gtmgl          1/1    Running  0        9m40s
monitoring-operator-67cc74f844-cdplp     2/2    Running  0        8m11s
nats-0                                   1/1    Running  0        13m
nats-1                                   1/1    Running  0        13m
nats-2                                   1/1    Running  0        12m
nautilus-769f5b74cd-k5jxm                1/1    Running  0        9m42s
nautilus-769f5b74cd-kd9gd                1/1    Running  0        8m59s
openapi-84f6ccd8ff-76kvp                 1/1    Running  0        9m34s
packages-6f59fc67dc-4g2f5                1/1    Running  0        9m52s
polaris-consul-consul-server-0           1/1    Running  0        13m
polaris-consul-consul-server-1           1/1    Running  0        13m
polaris-consul-consul-server-2           1/1    Running  0        13m
polaris-keycloak-0                       1/1    Running  0        8m7s
polaris-keycloak-1                       1/1    Running  0        5m49s
polaris-keycloak-2                       1/1    Running  0        5m15s
polaris-keycloak-db-0                    1/1    Running  0        8m6s
polaris-keycloak-db-1                    1/1    Running  0        5m49s
polaris-keycloak-db-2                    1/1    Running  0        4m57s
polaris-mongodb-0                        2/2    Running  0        13m
polaris-mongodb-1                        2/2    Running  0        12m
polaris-mongodb-2                        2/2    Running  0        12m
polaris-ui-565f56bf7b-zwr8b              1/1    Running  0        3m19s
polaris-vault-0                          1/1    Running  0        13m
polaris-vault-1                          1/1    Running  0        13m
polaris-vault-2                          1/1    Running  0        13m
public-metrics-6d86d66444-2wbzl          1/1    Running  0        9m30s
storage-backend-metrics-77c5d98dcd-dbhg5 1/1    Running  0        9m44s
storage-provider-78c885f57c-6zcv4        1/1    Running  0        9m36s
telegraf-ds-2l2m9                        1/1    Running  0        7m48s
telegraf-ds-qfzgh                        1/1    Running  0        7m48s
telegraf-ds-shrms                        1/1    Running  0        7m48s
telegraf-rs-bjpkt                        1/1    Running  0        7m48s
telemetry-service-6684696c64-qzfdf       1/1    Running  0        10m
tenancy-6596b6c54d-vmpsm                 1/1    Running  0        10m
traefik-7489dc59f9-6mnst                 1/1    Running  0        3m19s
traefik-7489dc59f9-xrkgg                 1/1    Running  0        3m4s
trident-svc-6c8dc458f5-jswcl             1/1    Running  0        10m
vault-controller-6b954f9b76-gz9nm        1/1    Running  0        11m
----
====
. （選用）若要確保安裝完成、您可以觀看 `acc-operator` 使用下列命令記錄。
+
[source, sh]
----
kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f
----
+

NOTE: `accHost` 叢集登錄是最後一項作業、如果失敗、也不會導致部署失敗。如果記錄中指出叢集登錄失敗、您可以透過新增叢集工作流程再次嘗試登錄 link:../get-started/setup_overview.html#add-cluster["在UI中"] 或API。

. 當所有Pod都在執行時、請確認安裝成功 (`READY` 是 `True`）並取得登入Astra Control Center時使用的一次性密碼：
+
[source, sh]
----
kubectl get AstraControlCenter -n netapp-acc
----
+
回應：

+
[listing]
----
NAME    UUID                                      VERSION     ADDRESS         READY
astra   ACC-9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f  22.08.1-26  10.111.111.111  True
----
+

IMPORTANT: 複製UUID值。密碼是 `ACC-` 接著是UUID值 (`ACC-[UUID]` 或者、在此範例中、 `ACC-9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f`）。





== 設定入口以進行負載平衡

您可以設定Kubernetes入口控制器來管理外部服務存取、例如叢集中的負載平衡。

本程序說明如何設定入口控制器 (`ingressType:Generic`）。這是Astra Control Center的預設動作。部署Astra Control Center之後、您需要設定入口控制器、以URL顯示Astra Control Center。


NOTE: 如果您不想設定入口控制器、可以設定 `ingressType:AccTraefik)`。Astra Control Center使用「負載平衡器」類型的服務 (`svc/traefik` （在Astra Control Center命名空間中）、並要求指派可存取的外部IP位址。如果您的環境允許負載平衡器、但您尚未設定負載平衡器、則可以使用MetalLB或其他外部服務負載平衡器、將外部IP位址指派給服務。在內部DNS伺服器組態中、您應該將Astra Control Center所選的DNS名稱指向負載平衡的IP位址。如需有關「負載平衡器」和入口服務類型的詳細資訊、請參閱 link:../get-started/requirements.html["需求"]。

這些步驟會因您使用的入口控制器類型而有所不同：

* Istio入口
* Nginx入口控制器
* OpenShift入口控制器


.您需要的產品
* 必要的 https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/["入口控制器"] 應已部署。
* 。 https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class["入口等級"] 應已建立對應於入口控制器的。
* 您使用的Kubernetes版本介於v1.19和v1.22之間、甚至包括在內。


.Istio入侵步驟
. 設定Istio入口。
+

NOTE: 此程序假設使用「預設」組態設定檔來部署Istio。 

. 收集或建立Ingress閘道所需的憑證和私密金鑰檔案。
+
您可以使用CA簽署或自我簽署的憑證。一般名稱必須是Astra位址（FQDN）。

+
命令範例： 

+
[source, sh]
----
openssl req -x509 -nodes -days 365 -newkey rsa:2048 
-keyout tls.key -out tls.crt
----
. 建立秘密 `tls secret name` 類型 `kubernetes.io/tls` 中的TLS私密金鑰和憑證 `istio-system namespace` 如TLS機密所述。
+
命令範例： 

+
[source, sh]
----
kubectl create secret tls [tls secret name] 
--key="tls.key"
--cert="tls.crt" -n istio-system
----
+

TIP: 機密名稱應與相符 `spec.tls.secretName` 提供於 `istio-ingress.yaml` 檔案：

. 在中部署入口資源 `netapp-acc` （或自訂命名）命名空間、使用v1beta1（Kubernetes版本低於或1.22的版本已過時）或v1資源類型來取代過時的或新的架構：
+
輸出：

+
[listing]
----
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: istio-system
spec:
  ingressClassName: istio
  tls:
  - hosts:
    - <ACC addess>
    secretName: [tls secret name]
  rules:
  - host: [ACC addess]
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: traefik
          servicePort: 80
----
+
如需v1新架構、請遵循下列範例：

+
[source, sh]
----
kubectl apply -f istio-Ingress.yaml
----
+
輸出：

+
[listing]
----
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: istio-system
spec:
  ingressClassName: istio
  tls:
  - hosts:
    - <ACC addess>
    secretName: [tls secret name]
  rules:
  - host: [ACC addess]
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik
            port:
              number: 80
----
. 如常部署Astra Control Center。
. 檢查入侵狀態：
+
[source, sh]
----
kubectl get ingress -n netapp-acc
----
+
回應：

+
[listing]
----
NAME    CLASS HOSTS             ADDRESS         PORTS   AGE
ingress istio astra.example.com 172.16.103.248  80, 443 1h
----


.適用於Nginvin像 控制器的步驟
. 建立類型的秘密[`kubernetes.io/tls`]用於中的TLS私密金鑰和憑證 `netapp-acc` （或自訂命名）命名空間、如所述 https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets["TLS機密"]。
. 在中部署入口資源 `netapp-acc` （或自訂命名）命名空間、使用任一項 `v1beta1` （在Kubernetes版本低於或1.22的版本中已過時）或 `v1` 過時或新架構的資源類型：
+
.. 適用於 `v1beta1` 過時的架構、請遵循以下範例：
+
[source, yaml]
----
apiVersion: extensions/v1beta1
Kind: IngressClass
metadata:
  name: ingress-acc
  namespace: [netapp-acc or custom namespace]
  annotations:
    kubernetes.io/ingress.class: [class name for nginx controller]
spec:
  tls:
  - hosts:
    - <ACC address>
    secretName: [tls secret name]
  rules:
  - host: [ACC address]
    http:
      paths:
      - backend:
        serviceName: traefik
        servicePort: 80
        pathType: ImplementationSpecific
----
.. 適用於 `v1` 新架構、請遵循以下範例：
+
[source, yaml]
----
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netapp-acc-ingress
  namespace: [netapp-acc or custom namespace]
spec:
  ingressClassName: [class name for nginx controller]
  tls:
  - hosts:
    - <ACC address>
    secretName: [tls secret name]
  rules:
  - host: <ACC addess>
    http:
      paths:
        - path:
          backend:
            service:
              name: traefik
              port:
                number: 80
          pathType: ImplementationSpecific
----




.OpenShift入口控制器的步驟
. 取得您的憑證、取得可供OpenShift路由使用的金鑰、憑證和CA檔案。
. 建立OpenShift路由：
+
[source, sh]
----
oc create route edge --service=traefik
--port=web -n [netapp-acc or custom namespace]
--insecure-policy=Redirect --hostname=<ACC address>
--cert=cert.pem --key=key.pem
----




== 登入Astra Control Center UI

安裝Astra Control Center之後、您將變更預設管理員的密碼、並登入Astra Control Center UI儀表板。

.步驟
. 在瀏覽器中、輸入您在中使用的FQDN `astraAddress` 在中  `astra_control_center_min.yaml` 請於何時進行 <<安裝Astra Control Center,您安裝了Astra Control Center>>。
. 出現提示時、請接受自我簽署的憑證。
+

NOTE: 您可以在登入後建立自訂憑證。

. 在Astra Control Center登入頁面、輸入您使用的值 `email` 在中 `astra_control_center_min.yaml` 請於何時進行 <<安裝Astra Control Center,您安裝了Astra Control Center>>，然後是一次性密碼 (`ACC-[UUID]`）。
+

NOTE: 如果您輸入錯誤密碼三次、系統將鎖定管理員帳戶15分鐘。

. 選擇*登入*。
. 出現提示時變更密碼。
+

NOTE: 如果這是您第一次登入、但您忘記密碼、而且尚未建立其他管理使用者帳戶、請聯絡NetApp支援部門以取得密碼恢復協助。

. （選用）移除現有的自我簽署TLS憑證、並以取代 link:../get-started/add-custom-tls-certificate.html["由憑證授權單位（CA）簽署的自訂TLS憑證"]。




== 疑難排解安裝

如果有任何服務存在 `Error` 狀態、您可以檢查記錄。尋找400到500範圍內的API回應代碼。這些都表示發生故障的地點。

.步驟
. 若要檢查Astra控制中心的操作員記錄、請輸入下列內容：
+
[source, sh]
----
kubectl logs --follow -n netapp-acc-operator $(kubectl get pods -n netapp-acc-operator -o name) -c manager
----




== 下一步

執行以完成部署 link:setup_overview.html["設定工作"]。
