---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: astra, control center, bugs, known issues, problems 
summary: 已知問題可識別可能導致您無法成功使用本產品版本的問題。 
---
= 已知問題
:hardbreaks:
:allow-uri-read: 
:source-highlighter: highlight.js
:icons: font
:imagesdir: ../media/release-notes/


已知問題可識別可能導致您無法成功使用本產品版本的問題。

下列已知問題會影響目前的版本：

.應用程式
*  of an app results in PV size larger than original PV
*  clones fail using a specific version of PostgreSQL
*  clones fail when using Service Account level OCP Security Context Constraints (SCC)
*  clones fail after an application is deployed with a set storage class
*  backups and snapshots fail if the volumesnapshotclass is added after a cluster is managed


.叢集
*  a cluster with Astra Control Center fails when default kubeconfig file contains more than one context


.其他問題
*  data management operations fail with Internal Service Error (500) when Astra Trident is offline
*  might fail with snapshot controller version 4.2.0




== 還原應用程式會導致PV大小大於原始PV

如果您在建立備份之後調整持續磁碟區的大小、然後從該備份還原、則持續磁碟區大小將會與PV的新大小相符、而非使用備份的大小。



== 使用特定版本的PostgreSQL時、應用程式複製失敗

同一個叢集內的應用程式複製作業、會持續失敗、並顯示Bitnami PostgreSQL 11.5.0圖表。若要成功複製、請使用舊版或更新版本的圖表。



== 使用服務帳戶層級OCP安全內容限制（SCC）時、應用程式複製失敗

如果在OpenShift Container Platform叢集的命名空間中、於服務帳戶層級設定原始的安全性內容限制、則應用程式複製可能會失敗。當應用程式複製失敗時、它會顯示在Astra Control Center的「託管應用程式」區域中、狀態為 `Removed`。請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Application_clone_is_failing_for_an_application_in_Astra_Control_Center["知識庫文章"^] 以取得更多資訊。



== 如果在管理叢集之後新增volumesnapshotClass、則應用程式備份和快照將會失敗

備份與快照無法使用 `UI 500 error` 在此案例中。因應措施是重新整理應用程式清單。



== 應用程式複製在以設定的儲存類別部署應用程式之後失敗

在部署應用程式並明確設定儲存類別之後（例如、 `helm install ...-set global.storageClass=netapp-cvs-perf-extreme`）之後、若想要複製應用程式、則目標叢集必須擁有原本指定的儲存類別。將具有明確設定儲存類別的應用程式複製到沒有相同儲存類別的叢集、將會失敗。在此案例中沒有任何恢復步驟。



== 使用Astra Control Center管理叢集失敗、因為預設的Kbeconfig檔案包含多個內容

您無法在其中使用多個叢集和內容的Kbeconfig。請參閱 link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Astra/Managing_cluster_with_Astra_Control_Center_may_fail_when_using_default_kubeconfig_file_contains_more_than_one_context["知識庫文章"^] 以取得更多資訊。



== 當Astra Trident離線時、應用程式資料管理作業會因內部服務錯誤（500）而失敗

如果應用程式叢集上的Astra Trident離線（並重新連線）、而且在嘗試應用程式資料管理時遇到500個內部服務錯誤、請重新啟動應用程式叢集中的所有Kubernetes節點、以還原功能。



== Snapshot控制器4.2.0版的快照可能會失敗

使用Kubernetes Snapshot-Controller（也稱為exter-snapshotter）4.2.0版搭配Kubernetes 1.20或1.21時、快照最終可能會開始失敗。若要避免這種情況發生、請使用不同的 https://kubernetes-csi.github.io/docs/snapshot-controller.html["支援的版本"^] Kubernetes版本1.20或1.21的外部快照功能（例如4.2.1版）。

. 執行POST呼叫、將更新的Kbeconfig檔案新增至 `/credentials` 端點並擷取指派的 `id` 來自回應本文。
. 從執行Put通話 `/clusters` 使用適當的叢集ID建立端點、然後設定 `credentialID` 至 `id` 上一步的價值。


完成這些步驟之後、與叢集相關的認證資料會更新、而且叢集應重新連線並將其狀態更新為 `available`。



== 如需詳細資訊、請參閱

* link:../release-notes/known-issues-ads.html["Astra Data Store預覽與此Astra Control Center版本的已知問題"]
* link:../release-notes/known-limitations.html["已知限制"]

